#
# This is a testing environment
#

version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./share-c3d-io-plugin:/var/www/html/user/plugins/share-c3d-io-plugin
    environment:
      - YOURLS_SITE=http://localhost:8080
      - YOURLS_USER=admin
      - YOURLS_PASS=admin
      - YOURLS_DB_HOST=mysql
      - YOURLS_DB_NAME=yourls
      - YOURLS_DB_USER=root
      - YOURLS_DB_PASS=root123

  mysql:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
